apiVersion: apps/v1
kind: Deployment
metadata:
  name: prices
spec:
  selector:
    matchLabels:
      app: prices
  replicas: 1
  template:
    metadata:
      labels:
        app: prices
    spec:
      containers:
      - name: prices
        image: andrelramos/listener-event-driven-platform
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        env:
        - name: REDIS_HOST
          value: redis://redis.default.svc.cluster.local
        - name: PYTHONUNBUFFERED
          value: "0"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prices-scaledobject
spec:
  scaleTargetRef:
    kind: Deployment
    name: prices
  pollingInterval: 60
  cooldownPeriod:  5
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: redis
    metadata:
      address: redis.default.svc.cluster.local:6379
      listName: shares
      listLength: "5"