apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-per
spec:
  selector:
    matchLabels:
      app: bff-per
  replicas: 1
  template:
    metadata:
      labels:
        app: bff-per
    spec:
      containers:
      - name: bff-per
        image: andrelramos/bff_price_earnings_ratio
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        env:
        - name: SHARES_API_ROUTE
          value: http://shares-api.default.svc.cluster.local
        - name: PYTHONUNBUFFERED
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: bff-per
spec:
  selector:
    app: bff-per
  ports:
  - port: 8080
    targetPort: 8080