apiVersion: apps/v1
kind: Deployment
metadata:
  name: shares-api-v1
spec:
  selector:
    matchLabels:
      app: shares-api-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: shares-api-v1
    spec:
      containers:
      - name: shares-api-v1
        image: andrelramos/bff-shares-event-driven-platform
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        env:
        - name: REDIS_HOST
          value: redis://redis.default.svc.cluster.local
        - name: REDIS_CACHE_HOST
          value: redis://cache.default.svc.cluster.local
        - name: PYTHONUNBUFFERED
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: shares-api-v1
spec:
  selector:
    app: shares-api-v1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shares-api-v1
spec:
  hosts:
  - "*"
  gateways:
  - shares-api-gateway
  http:
    - match:
      - uri:
          prefix: /
        queryParams:
          version:
            exact: v1        
      route:
      - destination:
          host: shares-api-v1