apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-shares
spec:
  selector:
    matchLabels:
      app: bff-shares
  replicas: 1
  template:
    metadata:
      labels:
        app: bff-shares
    spec:
      containers:
      - name: bff-shares
        image: andrelramos/bff-shares-event-driven-platform
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        env:
        - name: REDIS_HOST
          value: redis://redis.default.svc.cluster.local
        - name: REDIS_CACHE_HOST
          value: redis://cache.default.svc.cluster.local
        - name: PYTHONUNBUFFERED
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: bff-shares
spec:
  selector:
    app: bff-shares
  ports:
  - port: 8080
    targetPort: 8080